M48
; DRILL file {KiCad 8.0.2} date 2024-05-17T23:37:50+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-17T23:37:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0728
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0827
%
G90
G05
T1
X3.5811Y-1.6427
X3.5811Y-1.8573
T2
X3.4756Y-1.6545
X3.4756Y-1.8455
T3
X3.5752Y-1.5256
X3.5752Y-1.9744
M30
